version: "3"

services:
  identity:
    #build: src/DemoExchange.Identity
    image: demo_exchange.identity:0.0.2
    ports:
      - "8099:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 8099
      ASPNETCORE_Kestrel__Certificates__Default__Password: "PASSWORD"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/DemoExchange.pfx"
    volumes:
      - /opt/adc/htdocs/demo_exchange/docker:/https
      - /opt/adc/_log/demo_exchange:/log

  gateway:
    #build: src/DemoExchange.ApiGateway
    image: demo_exchange.api_gateway:0.0.2
    ports:
      - "8080:80"
      - "8090:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 8090
      ASPNETCORE_Kestrel__Certificates__Default__Password: "PASSWORD"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/DemoExchange.pfx"
    volumes:
      - /opt/adc/htdocs/demo_exchange/docker:/https
      - /opt/adc/_log/demo_exchange:/log
    depends_on:
      - identity
      - account
      - order
      - quote

  account:
    #build: src/DemoExchange.AccountService
    image: demo_exchange.account_service:0.0.2
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Password: "PASSWORD"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/DemoExchange.pfx"
    volumes:
      - /opt/adc/htdocs/demo_exchange/docker:/https
      - /opt/adc/_log/demo_exchange:/log
    depends_on:
      - sql

  order:
    #build: src/DemoExchange.OrderServiceGrpc
    image: demo_exchange.order_service_grpc:0.0.2
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Password: "PASSWORD"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/DemoExchange.pfx"
    volumes:
      - /opt/adc/htdocs/demo_exchange/docker:/https
      - /opt/adc/_log/demo_exchange:/log
    depends_on:
      - sql

  quote:
    #build: src/DemoExchange.QuoteService
    image: demo_exchange.quote_service:0.0.1
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Password: "PASSWORD"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/DemoExchange.pfx"
    volumes:
      - /opt/adc/htdocs/demo_exchange/docker:/https
      - /opt/adc/_log/demo_exchange:/log
    depends_on:
      - redis

  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "sqlserver-docker-PASSWORD"
    volumes:
      - /opt/adc/db/sqlserver/mount:/var/opt/mssql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass PASSWORD
    volumes:
      - /opt/adc/db/redis/mount:/data
