name: demo_exchange
description: DemoExchange frontend POC

publish_to: 'none'

version: 0.0.4-SNAPSHOT+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.2.0
  cupertino_icons: ^1.0.0
  grpc: ^2.3.0
  protobuf: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  #assets:
  #  - assets/localhost.crt
    